### ISSUE TITLE
Disabled (shaded) icon

### ISSUE THREAD

**Issue by acbg** [yep/Nightshift#4]
I can see the Nightshift icon on the bar, but it is shaded, so I can't use it. I seems like it's disabled. But it's enabled in the extensions manager. 
Now, when I disable it and enable again, I can actually see the icon normally again, push it, enable (or disable) Nightshift once, and then it gets back to shaded and can't use it anymore.

macOS Big Sur
Safari Version  16.3 (16614.4.6.11.4, 16614)

**Comment by Volodymyr-13** [comment]
@acbg I found that if you enable dark mode manually, then icon will be available. Thats a bug, so it enabled only when dark mode is active..

**Comment by Altereyo** [comment]
Same problem. Icon becomes enabled only when i manually turn my mac into dark mode
